from setuptools import find_packages, setup


setup(
    name="vcbench",
    version="0.1.0",
    description="VCBench: single-cell perturbation modeling and benchmarking framework",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    install_requires=[
        "torch==2.8.0",
        "lightning==2.5.5",
        "hydra-core==1.3.2",
        "hydra-colorlog==1.2.0",
        "omegaconf==2.3.0",
        "anndata==0.12.2",
        "scanpy==1.11.4",
        "numpy==1.26.4",
        "scipy==1.12.0",
        "pandas==2.3.3",
        "scikit-learn==1.7.2",
        "matplotlib==3.10.6",
        "seaborn==0.13.2",
        "adjustText==1.3.0",
        "tqdm==4.67.1",
        "tensorboard==2.20.0",
        "wandb==0.23.1",
        "rich==14.1.0",
        "torch-geometric==2.6.1",
        "geomloss==0.2.6",
        "transformers==4.56.2",
        "h5py==3.14.0",
        "pyarrow==21.0.0",
        "zarr==3.1.3",
    ],
    include_package_data=True,
    package_data={
        "VCBench": ["configs/**/*.yaml", "configs/**/*.yml"],
    },
    python_requires=">=3.10",
)
